### ISSUE TITLE
Waypoint Mission : WP: upload failed: coordinate frame is not supported

### ISSUE THREAD

**Issue by DesmondZhong** [mavlink/mavros#1064]
##This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

I try to use `mavros/mission/push` to send waypoint tables. In `Waypoint.msg`, I found the following definition for `frame`. 

```
# see enum MAV_FRAME
uint8 frame
uint8 FRAME_GLOBAL = 0
uint8 FRAME_LOCAL_NED = 1
uint8 FRAME_MISSION = 2
uint8 FRAME_GLOBAL_REL_ALT = 3
uint8 FRAME_LOCAL_ENU = 4
```

However, during my test in SITL, only `FRAME_GLOBAL` and `FRAME_GLOBAL_REL_ALT` works. If I use values 1, 2, 4. I'll get the error `WP: upload failed: coordinate frame is not supported`.

If this is the case, I can only use global frames to send Waypoint Missions. In other words, I need to set the longitude and latitude of points. However, if I want the drone to move to the north by 5 meters, converting "5 meters" to a latitude change is not convenient. If I can use local frames, the `x` and `y` units are already in meters. 

Could we use local frames to send missions? If we couldn't at this point, is there any way to get around it and send position in the unit of meter?

Thanks in advance!

### MAVROS version and platform

Mavros: 0.26.0
ROS: Kinetic
Ubuntu: 16.04

### Autopilot type and version

[  ] ArduPilot
[x] PX4

Version: ?3.7.1?

### Node logs

```
... logging to /home/desmond/.ros/log/9703c3ba-8f86-11e8-85f1-bea5f405bcc1/roslaunch-Intel-Aero-RTF-12408.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Intel-Aero-RTF:37474/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14540@loca...
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.000349065850399
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/frame_tf/body_frame_orientation: frd
 * /mavros/odometry/frame_tf/local_frame: vision_ned
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682389136
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: map
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    mavros (mavros/mavros_node)
    sitl (px4/px4)
    vehicle_spawn_Intel_Aero_RTF_12408_7987751955256816470 (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [12418]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 9703c3ba-8f86-11e8-85f1-bea5f405bcc1
process[rosout-1]: started with pid [12435]
started core service [/rosout]
process[sitl-2]: started with pid [12460]
node name: sitl
data path: /home/desmond/src/Firmware
commands file: /home/desmond/src/Firmware/posix-configs/SITL/init/ekf2/iris

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

571 WARNING: setRealtimeSched failed (not run as root?)
INFO  [dataman] Unknown restart, data manager file 'rootfs/fs/microsd/dataman' size is 11405132 bytes
process[gazebo-3]: started with pid [12470]
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
process[gazebo_gui-4]: started with pid [12477]
process[vehicle_spawn_Intel_Aero_RTF_12408_7987751955256816470-5]: started with pid [12482]
process[mavros-6]: started with pid [12483]
[ INFO] [1532466887.675845871]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1532466887.681194607]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1532466887.681555577]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1532466887.682245479]: GCS bridge disabled
[ INFO] [1532466887.727155248]: Plugin 3dr_radio loaded
[ INFO] [1532466887.736872662]: Plugin 3dr_radio initialized
[ INFO] [1532466887.737202619]: Plugin actuator_control loaded
[ INFO] [1532466887.758725165]: Plugin actuator_control initialized
[ INFO] [1532466887.767870580]: Plugin adsb loaded
[ INFO] [1532466887.786521491]: Plugin adsb initialized
[ INFO] [1532466887.786980926]: Plugin altitude loaded
[ INFO] [1532466887.794482431]: Plugin altitude initialized
[ INFO] [1532466887.794881215]: Plugin cam_imu_sync loaded
[ INFO] [1532466887.799184429]: Plugin cam_imu_sync initialized
[ INFO] [1532466887.799726278]: Plugin command loaded
[ INFO] [1532466887.833752146]: Plugin command initialized
[ INFO] [1532466887.834147291]: Plugin debug_value loaded
[ INFO] [1532466887.863849107]: Plugin debug_value initialized
[ INFO] [1532466887.863958047]: Plugin distance_sensor blacklisted
[ INFO] [1532466887.864422394]: Plugin fake_gps loaded
[ INFO] [1532466887.951663153]: Plugin fake_gps initialized
[ INFO] [1532466887.952222102]: Plugin ftp loaded
[ INFO] [1532466888.019235830]: Plugin ftp initialized
[ INFO] [1532466888.019717215]: Plugin global_position loaded
[ INFO] [1532466888.131146028]: Plugin global_position initialized
[ INFO] [1532466888.131643401]: Plugin hil loaded
[ INFO] [1532466888.221016307]: Plugin hil initialized
[ INFO] [1532466888.221545243]: Plugin home_position loaded
[ INFO] [1532466888.258801654]: Plugin home_position initialized
[ INFO] [1532466888.259270851]: Plugin imu loaded
[ INFO] [1532466888.323921068]: Plugin imu initialized
[ INFO] [1532466888.324396003]: Plugin local_position loaded
[ INFO] [1532466888.375080043]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1532466888.381161181]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1532466888.387585802]: Plugin local_position initialized
[ INFO] [1532466888.388296092]: Plugin manual_control loaded
[ INFO] [1532466888.415697123]: Plugin manual_control initialized
[ INFO] [1532466888.416119607]: Plugin mocap_pose_estimate loaded
[ INFO] [1532466888.451702846]: Plugin mocap_pose_estimate initialized
[ INFO] [1532466888.452046216]: Plugin obstacle_distance loaded
[ INFO] [1532466888.464932371]: Plugin obstacle_distance initialized
[ INFO] [1532466888.465326954]: Plugin odom loaded
[ INFO] [1532466888.485225442]: Plugin odom initialized
[ INFO] [1532466888.485958257]: Plugin param loaded
[ INFO] [1532466888.500289805]: Plugin param initialized
[ INFO] [1532466888.500700613]: Plugin px4flow loaded
[ INFO] [1532466888.539537494]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1532466888.566538268]: Plugin px4flow initialized
[ INFO] [1532466888.566650282]: Plugin rangefinder blacklisted
[ INFO] [1532466888.567203031]: Plugin rc_io loaded
[ INFO] [1532466888.571816440]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1532466888.604360778]: Plugin rc_io initialized
[ INFO] [1532466888.604461705]: Plugin safety_area blacklisted
[ INFO] [1532466888.604877701]: Plugin setpoint_accel loaded
[ INFO] [1532466888.630784539]: Plugin setpoint_accel initialized
[ INFO] [1532466888.631550730]: Plugin setpoint_attitude loaded
[ INFO] [1532466888.701886703]: Plugin setpoint_attitude initialized
[ INFO] [1532466888.702512466]: Plugin setpoint_position loaded
[ INFO] [1532466888.828014571]: Plugin setpoint_position initialized
[ INFO] [1532466888.828925915]: Plugin setpoint_raw loaded
[ INFO] [1532466888.915264483]: Plugin setpoint_raw initialized
[ INFO] [1532466888.915750293]: Plugin setpoint_velocity loaded
[ INFO] [1532466888.985359563]: Plugin setpoint_velocity initialized
[ INFO] [1532466888.986236418]: Plugin sys_status loaded
[ INFO] [1532466889.076764837]: Plugin sys_status initialized
[ INFO] [1532466889.077295298]: Plugin sys_time loaded
[ INFO] [1532466889.141085087]: TM: Timesync mode: MAVLINK
[ INFO] [1532466889.149727866]: Plugin sys_time initialized
[ INFO] [1532466889.150151425]: Plugin trajectory loaded
[ INFO] [1532466889.212105475]: Plugin trajectory initialized
[ INFO] [1532466889.212574935]: Plugin vfr_hud loaded
[ INFO] [1532466889.217204006]: Plugin vfr_hud initialized
[ INFO] [1532466889.217310309]: Plugin vibration blacklisted
[ INFO] [1532466889.217659228]: Plugin vision_pose_estimate loaded
[ INFO] [1532466889.266524069]: Plugin vision_pose_estimate initialized
[ INFO] [1532466889.266931152]: Plugin vision_speed_estimate loaded
[ INFO] [1532466889.295290104]: Plugin vision_speed_estimate initialized
[ INFO] [1532466889.295795090]: Plugin waypoint loaded
[ INFO] [1532466889.320297587]: Plugin waypoint initialized
[ INFO] [1532466889.320754521]: Plugin wind_estimation loaded
[ INFO] [1532466889.324695341]: Plugin wind_estimation initialized
[ INFO] [1532466889.324840244]: Autostarting mavlink via USB on PX4
[ INFO] [1532466889.325133737]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1532466889.325181463]: Built-in MAVLink package version: 2018.7.7
[ INFO] [1532466889.325227914]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1532466889.325281265]: MAVROS started. MY ID 1.240, TARGET ID 1.1
SpawnModel script started
[INFO] [1532466889.652699, 0.000000]: Loading model XML from file
[INFO] [1532466889.653644, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[INFO] [1532466889.658438, 0.000000]: Calling service /gazebo/spawn_sdf_model
[INFO] [1532466889.930842, 0.008000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1532466890.107316348, 0.034000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1532466890.108759290, 0.034000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[vehicle_spawn_Intel_Aero_RTF_12408_7987751955256816470-5] process has finished cleanly
log file: /home/desmond/.ros/log/9703c3ba-8f86-11e8-85f1-bea5f405bcc1/vehicle_spawn_Intel_Aero_RTF_12408_7987751955256816470-5*.log
[ INFO] [1532466890.455102360, 0.314000000]: Physics dynamic reconfigure ready.
[ INFO] [1532466890.465008441, 0.324000000]: Physics dynamic reconfigure ready.
INFO  [simulator] Got initial simulation data, running sim..
INFO  [pwm_out_sim] MODE_16PWM
INFO  [commander] Mission #3 loaded, 1 WPs, curr: 0
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14556 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14557 remote port 14540
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
pxh> INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log
INFO  [logger] Opened log file: rootfs/fs/microsd/log/2018-07-24/21_14_51.ulg
INFO  [mavlink] partner IP: 127.0.0.1
[ INFO] [1532466891.264468058, 1.098000000]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1532466891.392037278, 1.226000000]: IMU: High resolution IMU detected!
libGL error: failed to create drawable
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
[ INFO] [1532466892.199327263, 2.024000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1532466892.203779018, 2.028000000]: IMU: High resolution IMU detected!
[ INFO] [1532466892.330576375, 2.154000000]: IMU: Attitude quaternion IMU detected!
[ INFO] [1532466893.206573087, 3.028000000]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1532466893.206704752, 3.028000000]: VER: 1.1: Flight software:     01080000 (00000000003F889C)
[ INFO] [1532466893.206769866, 3.028000000]: VER: 1.1: Middleware software: 01080000 (00000000003F889C)
[ INFO] [1532466893.206823092, 3.028000000]: VER: 1.1: OS software:         04044cff (0000000000000000)
[ INFO] [1532466893.206898343, 3.028000000]: VER: 1.1: Board hardware:      00000001
[ INFO] [1532466893.206950770, 3.028000000]: VER: 1.1: VID/PID:             0000:0000
[ INFO] [1532466893.207031809, 3.028000000]: VER: 1.1: UID:                 0000000100000002
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
[ INFO] [1532466902.388100289, 12.024000000]: HP: requesting home position
[ INFO] [1532466905.727974873, 15.326000000]: WP: mission cleared
[ WARN] [1532466905.753664565, 15.352000000]: CMD: Unexpected command 176, result 0
WARN  [mavlink] IGN MISSION_ITEM: Busy
ERROR [mavlink] IGN MISSION_ITEM: Busy
[ERROR] [1532466905.769157217, 15.368000000]: WP: upload failed: coordinate frame is not supported
INFO  [commander] Takeoff detected
WARN  [commander_tests] Failsafe enabled: no datalink
INFO  [navigator] RTL HOME activated
INFO  [navigator] RTL: climb to 490 m (1 m above home)
[ INFO] [1532466907.434197761, 17.024000000]: WP: mission received
INFO  [navigator] RTL: return at 490 m (1 m above home)
INFO  [navigator] RTL: descend to 489 m (1 m above home)
INFO  [navigator] RTL: loiter 1.0s
INFO  [navigator] RTL: land at home
INFO  [commander] Landing detected
WARN  [navigator] No valid mission available, refusing takeoff.
WARN  [navigator] No valid mission available, refusing takeoff.
INFO  [logger] closed logfile, bytes written: 990210

```

### Diagnostics

```
header: 
  seq: 96
  stamp: 
    secs: 93
    nsecs: 500000000
  frame_id: ''
status: 
  - 
    level: 0
    name: "mavros: FCU connection"
    message: "connected"
    hardware_id: "udp://:14540@localhost:14557"
    values: 
      - 
        key: "Received packets:"
        value: "38242"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "97"
      - 
        key: "Tx sequence number:"
        value: "238"
      - 
        key: "Rx total bytes:"
        value: "1575612"
      - 
        key: "Tx total bytes:"
        value: "49530"
      - 
        key: "Rx speed:"
        value: "17547.000000"
      - 
        key: "Tx speed:"
        value: "537.000000"
  - 
    level: 0
    name: "mavros: GPS"
    message: "3D fix"
    hardware_id: "udp://:14540@localhost:14557"
    values: 
      - 
        key: "Satellites visible"
        value: "10"
      - 
        key: "Fix type"
        value: "3"
      - 
        key: "EPH (m)"
        value: "0.00"
      - 
        key: "EPV (m)"
        value: "0.00"
  - 
    level: 0
    name: "mavros: Heartbeat"
    message: "Normal"
    hardware_id: "udp://:14540@localhost:14557"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "89"
      - 
        key: "Frequency (Hz)"
        value: "1.000000"
      - 
        key: "Vehicle type"
        value: "Quadrotor"
      - 
        key: "Autopilot type"
        value: "PX4 Autopilot"
      - 
        key: "Mode"
        value: "AUTO.MISSION"
      - 
        key: "System status"
        value: "Standby"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "udp://:14540@localhost:14557"
    values: 
      - 
        key: "Sensor present"
        value: "0x0024002F"
      - 
        key: "Sensor enabled"
        value: "0x0020000F"
      - 
        key: "Sensor helth"
        value: "0x0024002F"
      - 
        key: "3D gyro"
        value: "Ok"
      - 
        key: "3D accelerometer"
        value: "Ok"
      - 
        key: "3D magnetometer"
        value: "Ok"
      - 
        key: "absolute pressure"
        value: "Ok"
      - 
        key: "AHRS subsystem health"
        value: "Ok"
      - 
        key: "CPU Load (%)"
        value: "0.0"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 0
    name: "mavros: Battery"
    message: "Normal"
    hardware_id: "udp://:14540@localhost:14557"
    values: 
      - 
        key: "Voltage"
        value: "12.15"
      - 
        key: "Current"
        value: "-1.0"
      - 
        key: "Remaining"
        value: "100.0"
  - 
    level: 0
    name: "mavros: Time Sync"
    message: "Normal"
    hardware_id: "udp://:14540@localhost:14557"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "925"
      - 
        key: "Frequency (Hz)"
        value: "10.000000"
      - 
        key: "Last RTT (ms)"
        value: "0.000000"
      - 
        key: "Mean RTT (ms)"
        value: "0.339459"
      - 
        key: "Last remote time (s)"
        value: "89.612241000"
      - 
        key: "Estimated time offset (s)"
        value: "3.888715378"

```

### Check ID

```
OK. I got messages from 1:1.

---
Received 6287 messages, from 1 addresses
sys:comp   list of messages
  1:1     0, 1, 2, 4, 140, 141, 147, 24, 26, 30, 31, 32, 33, 74, 76, 83, 85, 230, 105, 111, 241, 242, 245
Exception in thread Thread-2 (most likely raised during interpreter shutdown):Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/registration.py", line 275, in start
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/registration.py", line 307, in run
  File "/usr/lib/python2.7/threading.py", line 203, in release
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 235, in run
  File "/home/desmond/catkin_ws/src/mavros/mavros/scripts/checkid", line 90, in timer_cb
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 493, in signal_shutdown
  File "/usr/lib/python2.7/threading.py", line 946, in join
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

```

**Comment by DesmondZhong** [comment]
Interesting. I can't find any documentation of whether px4 supports it or not. I am gonna try Ardupilot and see if it works. I will update here. Thanks!

**Comment by DesmondZhong** [comment]
@TSC21 It seems that Ardupilot only supports global frames for waypoints too. Do you have any recommendation to control copters in the local frame using Ardupilot? Thanks!

**Comment by TSC21** [comment]
Use Offboard mode in PX4. Use Guided in Ardupilot.

**Comment by DesmondZhong** [comment]
Thanks! I'll explore a bit more!

**Comment by atharvasaraf** [comment]
Hello @DesmondZhong ! Were you able to use the local frames to feed waypoints to the PX4 or the Ardupilot?
