### ISSUE TITLE
include could not find load file: MavrosMavlink and EnableCXX11

### ISSUE THREAD

**Issue by Cristian-wp** [mavlink/mavros#1471]
### Issue details

Hi, for a project we have a repository in Azure DevOps and we are trying do create a common repository to work.
The structure of the repository is the following one:
````
(root project folder)
   catkin_ws (catkin workspace folder)
      build
      devel
      src
         Firmware (repository PX4/Firmware)
         avoidance (repository PX4/avoidance)
         sei-ros-beta (repository)
            mavlink
            mavros
            sample-package
            ... another package
            ... another repo
````
When I try to compile the cloned repository I get this errors:
````
Errors     << libmavconn:cmake /home/sei/AzureDevOps/SEI/catkin_ws/logs/libmavconn/build.cmake.000.log
CMake Error at /home/sei/AzureDevOps/SEI/catkin_ws/src/sei-ros-beta/mavros/libmavconn/CMakeLists.txt:15 (include):
  include could not find load file:

    EnableCXX11


CMake Error at /home/sei/AzureDevOps/SEI/catkin_ws/src/sei-ros-beta/mavros/libmavconn/CMakeLists.txt:16 (include):
  include could not find load file:

    MavrosMavlink
````
I had already check if there is any missing dependency with 
````
sei@sei:~/AzureDevOps/SEI/catkin_ws$ rosdep install --from-paths src --ignore-src
#All required rosdeps installed successfully
````
But as you can see all seems ok.
Can you please help me to solve this problem?

### MAVROS version and platform

Mavros: Release 1.3.0
ROS: Melodic
Ubuntu: 18.04 LTS

### Autopilot type and version

[  ] ArduPilot
[ x  ] PX4

Version: 1.10.1 (stable)

### Output of catkin build -c 

````
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
------------------------------------------------------------------------
[build] Found '12' packages in 0.0 seconds.                                    
[build] Updating package table.                                                
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                [ 1.4 seconds ]             
Starting  >>> mavlink                                                          
Starting  >>> mavros_msgs                                                      
Starting  >>> sample-package                                                   
Finished  <<< sample-package                       [ 2.8 seconds ]             
Finished  <<< mavlink                              [ 3.9 seconds ]             
Starting  >>> libmavconn                                                       
_______________________________________________________________________________
Errors     << libmavconn:cmake /home/sei/AzureDevOps/SEI/catkin_ws/logs/libmavconn/build.cmake.000.log
CMake Error at /home/sei/AzureDevOps/SEI/catkin_ws/src/sei-ros-beta/mavros/libmavconn/CMakeLists.txt:15 (include):
  include could not find load file:

    EnableCXX11


CMake Error at /home/sei/AzureDevOps/SEI/catkin_ws/src/sei-ros-beta/mavros/libmavconn/CMakeLists.txt:16 (include):
  include could not find load file:

    MavrosMavlink


CMake Warning at /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'mavlink' but neither 'mavlink_INCLUDE_DIRS'
  nor 'mavlink_LIBRARIES' is defined.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  CMakeLists.txt:25 (catkin_package)


<file:0 (/home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn/catkin_generated/mavlink.context.py)>:1: error: <type 'exceptions.ValueError'>: common dialect not listed!
Traceback (most recent call last):
  File "/usr/bin/empy", line 3302, in <module>
    if __name__ == '__main__': main()
  File "/usr/bin/empy", line 3300, in main
    invoke(sys.argv[1:])
  File "/usr/bin/empy", line 3264, in invoke
    interpreter.wrap(command, (target, name))
  File "/usr/bin/empy", line 2295, in wrap
    self.fail(e)
  File "/usr/bin/empy", line 2284, in wrap
    callable(*args)
  File "/usr/bin/empy", line 2391, in string
    self.safe(scanner, True, locals)
  File "/usr/bin/empy", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/bin/empy", line 2421, in parse
    token.run(self, locals)
  File "/usr/bin/empy", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/bin/empy", line 2595, in execute
    _exec(statements, self.globals, locals)
  File "/usr/bin/empy", line 42, in _exec
    exec("""exec code in globals""")
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 16, in <module>
ValueError: common dialect not listed!
CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn/catkin_generated/env_cached.sh
  "/usr/bin/python2" "/usr/bin/empy" "--raw-errors" "-F"
  "/home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn/catkin_generated/mavlink.context.py"
  "-o"
  "/home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn/catkin_generated/include/mavconn/mavlink_dialect.h"
  "/home/sei/AzureDevOps/SEI/catkin_ws/src/sei-ros-beta/mavros/libmavconn/include/mavconn/mavlink_dialect.h.em")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  CMakeLists.txt:58 (em_expand)


cd /home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn; catkin build --get-env libmavconn | catkin env -si  /usr/bin/cmake /home/sei/AzureDevOps/SEI/catkin_ws/src/sei-ros-beta/mavros/libmavconn --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/sei/AzureDevOps/SEI/catkin_ws/devel/.private/libmavconn -DCMAKE_INSTALL_PREFIX=/home/sei/AzureDevOps/SEI/catkin_ws/install; cd -
...............................................................................
Failed     << libmavconn:cmake                     [ Exited with code 1 ]      
Failed    <<< libmavconn                           [ 2.6 seconds ]             
Abandoned <<< mavros                               [ Depends on failed job libmavconn ]
Abandoned <<< mavros_extras                        [ Depends on failed job libmavconn ]
Abandoned <<< avoidance                            [ Depends on failed job libmavconn ]
Abandoned <<< global_planner                       [ Depends on failed job libmavconn ]
Abandoned <<< local_planner                        [ Depends on failed job libmavconn ]
Abandoned <<< px4                                  [ Depends on failed job libmavconn ]
Abandoned <<< safe_landing_planner                 [ Depends on failed job libmavconn ]
Abandoned <<< test_mavros                          [ Depends on failed job libmavconn ]
^C[build] Interrupted by user!                                                   
[build] Summary: 3 of 13 packages succeeded.                                   
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: 9 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 11.6 seconds total.                                           


````

The following one is the compilation output log file :

````
Not searching for unused variables given on the command line.
[36m--[0m The C compiler identification is GNU 8.4.0
[36m--[0m The CXX compiler identification is GNU 8.4.0
[36m--[0m Check for working C compiler: /usr/bin/cc
[36m--[0m Check for working C compiler: /usr/bin/cc -- works
[36m--[0m Detecting C compiler ABI info
[36m--[0m Detecting C compiler ABI info - done
[36m--[0m Detecting C compile features
[36m--[0m Detecting C compile features - done
[36m--[0m Check for working CXX compiler: /usr/bin/c++
[36m--[0m Check for working CXX compiler: /usr/bin/c++ -- works
[36m--[0m Detecting CXX compiler ABI info
[36m--[0m Detecting CXX compiler ABI info - done
[36m--[0m Detecting CXX compile features
[36m--[0m Detecting CXX compile features - done
[36m--[0m Using CATKIN_DEVEL_PREFIX: /home/sei/AzureDevOps/SEI/catkin_ws/devel/.private/libmavconn
[36m--[0m Using CMAKE_PREFIX_PATH: /home/sei/AzureDevOps/SEI/catkin_ws/devel;/opt/ros/melodic
[36m--[0m This workspace overlays: /home/sei/AzureDevOps/SEI/catkin_ws/devel;/opt/ros/melodic
[36m--[0m Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2")
[36m--[0m Using PYTHON_EXECUTABLE: /usr/bin/python2
[36m--[0m Using Debian Python package layout
[36m--[0m Using empy: /usr/bin/empy
[36m--[0m Using CATKIN_ENABLE_TESTING: ON
[36m--[0m Call enable_testing()
[36m--[0m Using CATKIN_TEST_RESULTS_DIR: /home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn/test_results
[36m--[0m Found gtest sources under '/usr/src/googletest': gtests will be built
[36m--[0m Found gmock sources under '/usr/src/googletest': gmock will be built
[36m--[0m Found PythonInterp: /usr/bin/python2 (found version "2.7.17")
[36m--[0m Looking for pthread.h
[36m--[0m Looking for pthread.h - found
[36m--[0m Looking for pthread_create
[36m--[0m Looking for pthread_create - not found
[36m--[0m Looking for pthread_create in pthreads
[36m--[0m Looking for pthread_create in pthreads - not found
[36m--[0m Looking for pthread_create in pthread
[36m--[0m Looking for pthread_create in pthread - found
[36m--[0m Found Threads: TRUE
[36m--[0m Using Python nosetests: /usr/bin/nosetests-2.7
[36m--[0m catkin 0.7.28
[36m--[0m BUILD_SHARED_LIBS is on
[36m--[0m Boost version: 1.65.1
[36m--[0m Found the following Boost libraries:
[36m--[0m   system
[31m[1mCMake Error[0m at /home/sei/AzureDevOps/SEI/catkin_ws/src/sei-ros-beta/mavros/libmavconn/CMakeLists.txt:15 (include):
  include could not find load file:

    EnableCXX11


[31m[1mCMake Error[0m at /home/sei/AzureDevOps/SEI/catkin_ws/src/sei-ros-beta/mavros/libmavconn/CMakeLists.txt:16 (include):
  include could not find load file:

    MavrosMavlink


[33m[1mCMake Warning[0m at /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'mavlink' but neither 'mavlink_INCLUDE_DIRS'
  nor 'mavlink_LIBRARIES' is defined.
[36mCall Stack (most recent call first):[0m
  /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  CMakeLists.txt:25 (catkin_package)


<file:0 (/home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn/catkin_generated/mavlink.context.py)>:1: error: <type 'exceptions.ValueError'>: common dialect not listed!
Traceback (most recent call last):
  File "/usr/bin/empy", line 3302, in <module>
    if __name__ == '__main__': main()
  File "/usr/bin/empy", line 3300, in main
    invoke(sys.argv[1:])
  File "/usr/bin/empy", line 3264, in invoke
    interpreter.wrap(command, (target, name))
  File "/usr/bin/empy", line 2295, in wrap
    self.fail(e)
  File "/usr/bin/empy", line 2284, in wrap
    callable(*args)
  File "/usr/bin/empy", line 2391, in string
    self.safe(scanner, True, locals)
  File "/usr/bin/empy", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/bin/empy", line 2421, in parse
    token.run(self, locals)
  File "/usr/bin/empy", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/bin/empy", line 2595, in execute
    _exec(statements, self.globals, locals)
  File "/usr/bin/empy", line 42, in _exec
    exec("""exec code in globals""")
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 16, in <module>
ValueError: common dialect not listed!
[31m[1mCMake Error[0m at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn/catkin_generated/env_cached.sh
  "/usr/bin/python2" "/usr/bin/empy" "--raw-errors" "-F"
  "/home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn/catkin_generated/mavlink.context.py"
  "-o"
  "/home/sei/AzureDevOps/SEI/catkin_ws/build/libmavconn/catkin_generated/include/mavconn/mavlink_dialect.h"
  "/home/sei/AzureDevOps/SEI/catkin_ws/src/sei-ros-beta/mavros/libmavconn/include/mavconn/mavlink_dialect.h.em")
  returned error code 1
[36mCall Stack (most recent call first):[0m
  /opt/ros/melodic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  CMakeLists.txt:58 (em_expand)


[36m--[0m Configuring incomplete, errors occurred!

````

**Comment by vooon** [comment]
Somehting wrong with cmake config. That modules here: https://github.com/mavlink/mavros/tree/master/libmavconn/cmake/Modules

**Comment by Cristian-wp** [comment]
Thank you @vooon  for the reply, do you know how to fix it?
I have also try this two ways:
1) Use the 1.2 version and the error disappear
2) Reinstall the system, but the error persist

How can I correctly modify the cmake config?
