### ISSUE TITLE
libmavconn "common dialect not listed!" in ROS Noetic Ubuntu Focal armhf

### ISSUE THREAD

**Issue by sloretz** [mavlink/mavros#1523]
### Issue details

The ROS Noetic binary job for libmavconn is currently failing on armhf using Ubuntu Focal

https://build.ros.org/view/Nbin_ufhf_uFhf/job/Nbin_ufhf_uFhf__libmavconn__ubuntu_focal_armhf__binary/17/

```
23:08:00 <file:0 (/tmp/binarydeb/ros-noetic-libmavconn-1.5.1/obj-arm-linux-gnueabihf/catkin_generated/mavlink.context.py)>:1: error: <class 'ValueError'>: common dialect not listed!
23:08:00 Traceback (most recent call last):
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 3302, in <module>
23:08:00     if __name__ == '__main__': main()
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 3300, in main
23:08:00     invoke(sys.argv[1:])
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 3264, in invoke
23:08:00     interpreter.wrap(command, (target, name))
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 2295, in wrap
23:08:00     self.fail(e)
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 2284, in wrap
23:08:00     callable(*args)
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 2391, in string
23:08:00     self.safe(scanner, True, locals)
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 2401, in safe
23:08:00     self.parse(scanner, locals)
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 2421, in parse
23:08:00     token.run(self, locals)
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 1425, in run
23:08:00     interpreter.execute(self.code, locals)
23:08:00   File "/usr/lib/python3/dist-packages/em.py", line 2595, in execute
23:08:00     _exec(statements, self.globals, locals)
23:08:00   File "<string>", line 1, in <module>
23:08:00   File "<string>", line 16, in <module>
23:08:00 ValueError: common dialect not listed!
23:08:00 CMake Error at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
23:08:00   
23:08:00   execute_process(/tmp/binarydeb/ros-noetic-libmavconn-1.5.1/obj-arm-linux-gnueabihf/catkin_generated/env_cached.sh
23:08:00   "/usr/bin/python3" "/usr/lib/python3/dist-packages/em.py" "--raw-errors"
23:08:00   "-F"
23:08:00   "/tmp/binarydeb/ros-noetic-libmavconn-1.5.1/obj-arm-linux-gnueabihf/catkin_generated/mavlink.context.py"
23:08:00   "-o"
23:08:00   "/tmp/binarydeb/ros-noetic-libmavconn-1.5.1/obj-arm-linux-gnueabihf/catkin_generated/include/mavconn/mavlink_dialect.h"
23:08:00   "/tmp/binarydeb/ros-noetic-libmavconn-1.5.1/include/mavconn/mavlink_dialect.h.em")
23:08:00   returned error code 1
23:08:00 Call Stack (most recent call first):
23:08:00   /opt/ros/noetic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
23:08:00   CMakeLists.txt:58 (em_expand)
23:08:00 
23:08:00 
23:08:00 -- Configuring incomplete, errors occurred!
23:08:00 See also "/tmp/binarydeb/ros-noetic-libmavconn-1.5.1/obj-arm-linux-gnueabihf/CMakeFiles/CMakeOutput.log".
23:08:00 See also "/tmp/binarydeb/ros-noetic-libmavconn-1.5.1/obj-arm-linux-gnueabihf/CMakeFiles/CMakeError.log".
23:08:00 	cd obj-arm-linux-gnueabihf && tail -v -n \+0 CMakeCache.txt
```

It appears an exception is raised here: https://github.com/mavlink/mavros/blob/efb533174e47aced9489526f2c8ae0be633e45e9/libmavconn/mavlink.context.py.in#L16

### MAVROS version and platform

Mavros: 1.5.1-1
ROS: Noetic
Ubuntu: 20.04

### Autopilot type and version

N/A ?

### Node logs

N/A

### Diagnostics
N/A

### Check ID

N/A ?

**Comment by vooon** [comment]
Hello, i'm not quite sure what is the reason. I tested inside docker container - all seems ok.
Would try to get armhf target up on the weekend.
