### ISSUE TITLE
mavROS unable to talk to BlueROV2's Pixhawk

### ISSUE THREAD

**Issue by Firestarss** [mavlink/mavros#1593]
----

### Issue details

So I just recently downloaded mavROS in order to be able to use ROS to interface with my [BlueROV2](https://bluerobotics.com/store/rov/bluerov2/). I got the mavROS node setup and running but every time I try to issue a command (such as `rosservice call /mavros/cmd/arming "value: true"`) I get the following errors:
```
success: False
result: 4
```
This is returned for just about every single command I run.

### MAVROS version and platform

Mavros: Unknown... let me know where to find this and I'll add it in
ROS: Noetic
Ubuntu: 20.04

### Autopilot type and version

[  ] ArduPilot
[ X] PX4 (Onboard Pi running arduSub. Pi takes commands from a topside computer and sends mavlink commands to the PX4)

Version: Unknown... let me know where to find this and I'll add it in

### Node logs

```
bluerov@bluerov2:~$ roslaunch mavros px4.launch fcu_url:=udp://:14555@192.168.2.1:14555
... logging to /home/bluerov/.ros/log/0ec3e51a-e8da-11eb-a6c9-5f9ad241a2cf/roslaunch-bluerov2-13889.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://bluerov2:35281/

SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

PARAMETERS
 * /mavros/cmd/use_comp_id_system_control: False
 * /mavros/conn/heartbeat_rate: 1.0
 * /mavros/conn/system_time_rate: 1.0
 * /mavros/conn/timeout: 10.0
 * /mavros/conn/timesync_rate: 10.0
 * /mavros/distance_sensor/hrlv_ez4_pub/field_of_view: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/frame_id: hrlv_ez4_sonar
 * /mavros/distance_sensor/hrlv_ez4_pub/id: 0
 * /mavros/distance_sensor/hrlv_ez4_pub/orientation: PITCH_270
 * /mavros/distance_sensor/hrlv_ez4_pub/send_tf: True
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/hrlv_ez4_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/laser_1_sub/id: 3
 * /mavros/distance_sensor/laser_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/laser_1_sub/subscriber: True
 * /mavros/distance_sensor/lidarlite_pub/field_of_view: 0.0
 * /mavros/distance_sensor/lidarlite_pub/frame_id: lidarlite_laser
 * /mavros/distance_sensor/lidarlite_pub/id: 1
 * /mavros/distance_sensor/lidarlite_pub/orientation: PITCH_270
 * /mavros/distance_sensor/lidarlite_pub/send_tf: True
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/x: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/y: 0.0
 * /mavros/distance_sensor/lidarlite_pub/sensor_position/z: -0.1
 * /mavros/distance_sensor/sonar_1_sub/horizontal_fov_ratio: 1.0
 * /mavros/distance_sensor/sonar_1_sub/id: 2
 * /mavros/distance_sensor/sonar_1_sub/orientation: PITCH_270
 * /mavros/distance_sensor/sonar_1_sub/subscriber: True
 * /mavros/distance_sensor/sonar_1_sub/vertical_fov_ratio: 1.0
 * /mavros/fake_gps/eph: 2.0
 * /mavros/fake_gps/epv: 2.0
 * /mavros/fake_gps/fix_type: 3
 * /mavros/fake_gps/geo_origin/alt: 408.0
 * /mavros/fake_gps/geo_origin/lat: 47.3667
 * /mavros/fake_gps/geo_origin/lon: 8.55
 * /mavros/fake_gps/gps_rate: 5.0
 * /mavros/fake_gps/mocap_transform: True
 * /mavros/fake_gps/satellites_visible: 5
 * /mavros/fake_gps/tf/child_frame_id: fix
 * /mavros/fake_gps/tf/frame_id: map
 * /mavros/fake_gps/tf/listen: False
 * /mavros/fake_gps/tf/rate_limit: 10.0
 * /mavros/fake_gps/tf/send: False
 * /mavros/fake_gps/use_mocap: True
 * /mavros/fake_gps/use_vision: False
 * /mavros/fcu_protocol: v2.0
 * /mavros/fcu_url: udp://:14555@192....
 * /mavros/gcs_url: 
 * /mavros/global_position/child_frame_id: base_link
 * /mavros/global_position/frame_id: map
 * /mavros/global_position/gps_uere: 1.0
 * /mavros/global_position/rot_covariance: 99999.0
 * /mavros/global_position/tf/child_frame_id: base_link
 * /mavros/global_position/tf/frame_id: map
 * /mavros/global_position/tf/global_frame_id: earth
 * /mavros/global_position/tf/send: False
 * /mavros/global_position/use_relative_alt: True
 * /mavros/image/frame_id: px4flow
 * /mavros/imu/angular_velocity_stdev: 0.0003490659 // 0...
 * /mavros/imu/frame_id: base_link
 * /mavros/imu/linear_acceleration_stdev: 0.0003
 * /mavros/imu/magnetic_stdev: 0.0
 * /mavros/imu/orientation_stdev: 1.0
 * /mavros/landing_target/camera/fov_x: 2.0071286398
 * /mavros/landing_target/camera/fov_y: 2.0071286398
 * /mavros/landing_target/image/height: 480
 * /mavros/landing_target/image/width: 640
 * /mavros/landing_target/land_target_type: VISION_FIDUCIAL
 * /mavros/landing_target/listen_lt: False
 * /mavros/landing_target/mav_frame: LOCAL_NED
 * /mavros/landing_target/target_size/x: 0.3
 * /mavros/landing_target/target_size/y: 0.3
 * /mavros/landing_target/tf/child_frame_id: camera_center
 * /mavros/landing_target/tf/frame_id: landing_target
 * /mavros/landing_target/tf/listen: False
 * /mavros/landing_target/tf/rate_limit: 10.0
 * /mavros/landing_target/tf/send: True
 * /mavros/local_position/frame_id: map
 * /mavros/local_position/tf/child_frame_id: base_link
 * /mavros/local_position/tf/frame_id: map
 * /mavros/local_position/tf/send: False
 * /mavros/local_position/tf/send_fcu: False
 * /mavros/mission/pull_after_gcs: True
 * /mavros/mission/use_mission_item_int: True
 * /mavros/mocap/use_pose: True
 * /mavros/mocap/use_tf: False
 * /mavros/odometry/fcu/odom_child_id_des: base_link
 * /mavros/odometry/fcu/odom_parent_id_des: map
 * /mavros/plugin_blacklist: ['safety_area', '...
 * /mavros/plugin_whitelist: []
 * /mavros/px4flow/frame_id: px4flow
 * /mavros/px4flow/ranger_fov: 0.118682
 * /mavros/px4flow/ranger_max_range: 5.0
 * /mavros/px4flow/ranger_min_range: 0.3
 * /mavros/safety_area/p1/x: 1.0
 * /mavros/safety_area/p1/y: 1.0
 * /mavros/safety_area/p1/z: 1.0
 * /mavros/safety_area/p2/x: -1.0
 * /mavros/safety_area/p2/y: -1.0
 * /mavros/safety_area/p2/z: -1.0
 * /mavros/setpoint_accel/send_force: False
 * /mavros/setpoint_attitude/reverse_thrust: False
 * /mavros/setpoint_attitude/tf/child_frame_id: target_attitude
 * /mavros/setpoint_attitude/tf/frame_id: map
 * /mavros/setpoint_attitude/tf/listen: False
 * /mavros/setpoint_attitude/tf/rate_limit: 50.0
 * /mavros/setpoint_attitude/use_quaternion: False
 * /mavros/setpoint_position/mav_frame: LOCAL_NED
 * /mavros/setpoint_position/tf/child_frame_id: target_position
 * /mavros/setpoint_position/tf/frame_id: map
 * /mavros/setpoint_position/tf/listen: False
 * /mavros/setpoint_position/tf/rate_limit: 50.0
 * /mavros/setpoint_raw/thrust_scaling: 1.0
 * /mavros/setpoint_velocity/mav_frame: LOCAL_NED
 * /mavros/startup_px4_usb_quirk: True
 * /mavros/sys/disable_diag: False
 * /mavros/sys/min_voltage: 10.0
 * /mavros/target_component_id: 1
 * /mavros/target_system_id: 1
 * /mavros/tdr_radio/low_rssi: 40
 * /mavros/time/time_ref_source: fcu
 * /mavros/time/timesync_avg_alpha: 0.6
 * /mavros/time/timesync_mode: MAVLINK
 * /mavros/vibration/frame_id: base_link
 * /mavros/vision_pose/tf/child_frame_id: vision_estimate
 * /mavros/vision_pose/tf/frame_id: odom
 * /mavros/vision_pose/tf/listen: False
 * /mavros/vision_pose/tf/rate_limit: 10.0
 * /mavros/vision_speed/listen_twist: True
 * /mavros/vision_speed/twist_cov: True
 * /mavros/wheel_odometry/child_frame_id: base_link
 * /mavros/wheel_odometry/count: 2
 * /mavros/wheel_odometry/frame_id: odom
 * /mavros/wheel_odometry/send_raw: True
 * /mavros/wheel_odometry/send_twist: False
 * /mavros/wheel_odometry/tf/child_frame_id: base_link
 * /mavros/wheel_odometry/tf/frame_id: odom
 * /mavros/wheel_odometry/tf/send: False
 * /mavros/wheel_odometry/use_rpm: False
 * /mavros/wheel_odometry/vel_error: 0.1
 * /mavros/wheel_odometry/wheel0/radius: 0.05
 * /mavros/wheel_odometry/wheel0/x: 0.0
 * /mavros/wheel_odometry/wheel0/y: -0.15
 * /mavros/wheel_odometry/wheel1/radius: 0.05
 * /mavros/wheel_odometry/wheel1/x: 0.0
 * /mavros/wheel_odometry/wheel1/y: 0.15
 * /rosdistro: noetic
 * /rosversion: 1.15.11

NODES
  /
    mavros (mavros/mavros_node)

ROS_MASTER_URI=http://localhost:11311

process[mavros-1]: started with pid [13904]
[ INFO] [1626735387.960744314]: FCU URL: udp://:14555@192.168.2.1:14555
[ INFO] [1626735387.965326709]: udp0: Bind address: 0.0.0.0:14555
[ INFO] [1626735387.965474560]: udp0: Remote address: 192.168.2.1:14555
[ INFO] [1626735387.965712703]: GCS bridge disabled
[ INFO] [1626735387.988296803]: Plugin 3dr_radio loaded
[ INFO] [1626735387.991338187]: Plugin 3dr_radio initialized
[ INFO] [1626735387.991538026]: Plugin actuator_control loaded
[ INFO] [1626735387.998140208]: Plugin actuator_control initialized
[ INFO] [1626735388.005832693]: Plugin adsb loaded
[ INFO] [1626735388.012194978]: Plugin adsb initialized
[ INFO] [1626735388.012401147]: Plugin altitude loaded
[ INFO] [1626735388.014203936]: Plugin altitude initialized
[ INFO] [1626735388.014374925]: Plugin cam_imu_sync loaded
[ INFO] [1626735388.015502543]: Plugin cam_imu_sync initialized
[ INFO] [1626735388.015694082]: Plugin command loaded
[ INFO] [1626735388.027204811]: Plugin command initialized
[ INFO] [1626735388.027468571]: Plugin companion_process_status loaded
[ INFO] [1626735388.032321536]: Plugin companion_process_status initialized
[ INFO] [1626735388.032580754]: Plugin debug_value loaded
[ INFO] [1626735388.042525604]: Plugin debug_value initialized
[ INFO] [1626735388.042619776]: Plugin distance_sensor blacklisted
[ INFO] [1626735388.042793441]: Plugin esc_status loaded
[ INFO] [1626735388.045140436]: Plugin esc_status initialized
[ INFO] [1626735388.045346676]: Plugin fake_gps loaded
[ INFO] [1626735388.078407079]: Plugin fake_gps initialized
[ INFO] [1626735388.078669436]: Plugin ftp loaded
[ INFO] [1626735388.092188812]: Plugin ftp initialized
[ INFO] [1626735388.092473606]: Plugin geofence loaded
[ INFO] [1626735388.099264168]: Plugin geofence initialized
[ INFO] [1626735388.099549453]: Plugin global_position loaded
[ INFO] [1626735388.136424285]: Plugin global_position initialized
[ INFO] [1626735388.136684506]: Plugin gps_rtk loaded
[ INFO] [1626735388.143852185]: Plugin gps_rtk initialized
[ INFO] [1626735388.144063599]: Plugin gps_status loaded
[ INFO] [1626735388.148666680]: Plugin gps_status initialized
[ INFO] [1626735388.148942383]: Plugin hil loaded
[ INFO] [1626735388.177124074]: Plugin hil initialized
[ INFO] [1626735388.177402699]: Plugin home_position loaded
[ INFO] [1626735388.184369996]: Plugin home_position initialized
[ INFO] [1626735388.184594661]: Plugin imu loaded
[ INFO] [1626735388.200376823]: Plugin imu initialized
[ INFO] [1626735388.200639367]: Plugin landing_target loaded
[ INFO] [1626735388.232283401]: Plugin landing_target initialized
[ INFO] [1626735388.232569863]: Plugin local_position loaded
[ INFO] [1626735388.247312565]: Plugin local_position initialized
[ INFO] [1626735388.247639235]: Plugin log_transfer loaded
[ INFO] [1626735388.253233153]: Plugin log_transfer initialized
[ INFO] [1626735388.253502055]: Plugin manual_control loaded
[ INFO] [1626735388.260081019]: Plugin manual_control initialized
[ INFO] [1626735388.260371750]: Plugin mocap_pose_estimate loaded
[ INFO] [1626735388.269486858]: Plugin mocap_pose_estimate initialized
[ INFO] [1626735388.269713701]: Plugin mount_control loaded
[ INFO] [1626735388.277702340]: Plugin mount_control initialized
[ INFO] [1626735388.277928008]: Plugin obstacle_distance loaded
[ INFO] [1626735388.284172897]: Plugin obstacle_distance initialized
[ INFO] [1626735388.284405624]: Plugin odom loaded
[ INFO] [1626735388.294415498]: Plugin odom initialized
[ INFO] [1626735388.294691347]: Plugin onboard_computer_status loaded
[ INFO] [1626735388.300423472]: Plugin onboard_computer_status initialized
[ INFO] [1626735388.300660673]: Plugin param loaded
[ INFO] [1626735388.306595109]: Plugin param initialized
[ INFO] [1626735388.306810180]: Plugin play_tune loaded
[ INFO] [1626735388.312349353]: Plugin play_tune initialized
[ INFO] [1626735388.312564870]: Plugin px4flow loaded
[ INFO] [1626735388.328856106]: Plugin px4flow initialized
[ INFO] [1626735388.329143007]: Plugin rallypoint loaded
[ INFO] [1626735388.335033345]: Plugin rallypoint initialized
[ INFO] [1626735388.335130743]: Plugin rangefinder blacklisted
[ INFO] [1626735388.335332731]: Plugin rc_io loaded
[ INFO] [1626735388.342441307]: Plugin rc_io initialized
[ INFO] [1626735388.342524305]: Plugin safety_area blacklisted
[ INFO] [1626735388.342765277]: Plugin setpoint_accel loaded
[ INFO] [1626735388.349961499]: Plugin setpoint_accel initialized
[ INFO] [1626735388.350274221]: Plugin setpoint_attitude loaded
[ INFO] [1626735388.371491919]: Plugin setpoint_attitude initialized
[ INFO] [1626735388.371772431]: Plugin setpoint_position loaded
[ INFO] [1626735388.406907938]: Plugin setpoint_position initialized
[ INFO] [1626735388.407239182]: Plugin setpoint_raw loaded
[ INFO] [1626735388.425340290]: Plugin setpoint_raw initialized
[ INFO] [1626735388.425613096]: Plugin setpoint_trajectory loaded
[ INFO] [1626735388.435629432]: Plugin setpoint_trajectory initialized
[ INFO] [1626735388.435885262]: Plugin setpoint_velocity loaded
[ INFO] [1626735388.447488858]: Plugin setpoint_velocity initialized
[ INFO] [1626735388.447829552]: Plugin sys_status loaded
[ INFO] [1626735388.471700553]: Plugin sys_status initialized
[ INFO] [1626735388.471991085]: Plugin sys_time loaded
[ INFO] [1626735388.485541286]: TM: Timesync mode: MAVLINK
[ INFO] [1626735388.488349330]: Plugin sys_time initialized
[ INFO] [1626735388.488633264]: Plugin trajectory loaded
[ INFO] [1626735388.501453530]: Plugin trajectory initialized
[ INFO] [1626735388.501756322]: Plugin vfr_hud loaded
[ INFO] [1626735388.503282274]: Plugin vfr_hud initialized
[ INFO] [1626735388.503381605]: Plugin vibration blacklisted
[ INFO] [1626735388.503605244]: Plugin vision_pose_estimate loaded
[ INFO] [1626735388.522507514]: Plugin vision_pose_estimate initialized
[ INFO] [1626735388.522819329]: Plugin vision_speed_estimate loaded
[ INFO] [1626735388.532779934]: Plugin vision_speed_estimate initialized
[ INFO] [1626735388.533084131]: Plugin waypoint loaded
[ INFO] [1626735388.543797461]: Plugin waypoint initialized
[ INFO] [1626735388.543905934]: Plugin wheel_odometry blacklisted
[ INFO] [1626735388.544144258]: Plugin wind_estimation loaded
[ INFO] [1626735388.545406176]: Plugin wind_estimation initialized
[ INFO] [1626735388.545510528]: Autostarting mavlink via USB on PX4
[ INFO] [1626735388.545610994]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1626735388.545668275]: Built-in MAVLink package version: 2021.6.6
[ INFO] [1626735388.545762141]: udp0: Remote address: 192.168.2.1:14555
[ INFO] [1626735388.545935413]: Known MAVLink dialects: common ardupilotmega ASLUAV all development icarous matrixpilot paparazzi standard uAvionix ualberta
[ INFO] [1626735388.546040117]: MAVROS started. MY ID 1.240, TARGET ID 1.1
```
The following appear in the node logs when I run a mavros service (`rosservice call /mavros/cmd/arming "value: true"` and `rosservice call /mavros/cmd/command 0 183 1 9 1500 0 0 0 0 0` respectively:
```
[ WARN] [1626735449.636499992]: CMD: Command 400 -- wait ack timeout
[ WARN] [1626735458.971009135]: CMD: Command 183 -- wait ack timeout
```

### Diagnostics

```
header: 
  seq: 130
  stamp: 
    secs: 1626735553
    nsecs: 546730234
  frame_id: ''
status: 
  - 
    level: 1
    name: "mavros: FCU connection"
    message: "not connected"
    hardware_id: "udp://:14555@192.168.2.1:14555"
    values: 
      - 
        key: "Received packets:"
        value: "3632"
      - 
        key: "Dropped packets:"
        value: "0"
      - 
        key: "Buffer overruns:"
        value: "0"
      - 
        key: "Parse errors:"
        value: "0"
      - 
        key: "Rx sequence number:"
        value: "48"
      - 
        key: "Tx sequence number:"
        value: "0"
      - 
        key: "Rx total bytes:"
        value: "99119"
      - 
        key: "Tx total bytes:"
        value: "99119"
      - 
        key: "Rx speed:"
        value: "600.000000"
      - 
        key: "Tx speed:"
        value: "600.000000"
  - 
    level: 2
    name: "mavros: GPS"
    message: "No satellites"
    hardware_id: "udp://:14555@192.168.2.1:14555"
    values: 
      - 
        key: "Satellites visible"
        value: "0"
      - 
        key: "Fix type"
        value: "0"
      - 
        key: "EPH (m)"
        value: "Unknown"
      - 
        key: "EPV (m)"
        value: "Unknown"
  - 
    level: 2
    name: "mavros: Heartbeat"
    message: "No events recorded."
    hardware_id: "udp://:14555@192.168.2.1:14555"
    values: 
      - 
        key: "Heartbeats since startup"
        value: "0"
      - 
        key: "Frequency (Hz)"
        value: "0.000000"
      - 
        key: "Vehicle type"
        value: "Generic micro air vehicle"
      - 
        key: "Autopilot type"
        value: "Generic autopilot"
      - 
        key: "Mode"
        value: ''
      - 
        key: "System status"
        value: "Uninit"
  - 
    level: 0
    name: "mavros: System"
    message: "Normal"
    hardware_id: "udp://:14555@192.168.2.1:14555"
    values: 
      - 
        key: "Sensor present"
        value: "0x00000000"
      - 
        key: "Sensor enabled"
        value: "0x00000000"
      - 
        key: "Sensor health"
        value: "0x00000000"
      - 
        key: "CPU Load (%)"
        value: "0.0"
      - 
        key: "Drop rate (%)"
        value: "0.0"
      - 
        key: "Errors comm"
        value: "0"
      - 
        key: "Errors count #1"
        value: "0"
      - 
        key: "Errors count #2"
        value: "0"
      - 
        key: "Errors count #3"
        value: "0"
      - 
        key: "Errors count #4"
        value: "0"
  - 
    level: 2
    name: "mavros: Battery"
    message: "No data"
    hardware_id: "udp://:14555@192.168.2.1:14555"
    values: 
      - 
        key: "Voltage"
        value: "-1.00"
      - 
        key: "Current"
        value: "0.0"
      - 
        key: "Remaining"
        value: "0.0"
  - 
    level: 0
    name: "mavros: Time Sync"
    message: "Normal"
    hardware_id: "udp://:14555@192.168.2.1:14555"
    values: 
      - 
        key: "Timesyncs since startup"
        value: "1650"
      - 
        key: "Frequency (Hz)"
        value: "9.999806"
      - 
        key: "Last RTT (ms)"
        value: "0.246225"
      - 
        key: "Mean RTT (ms)"
        value: "0.225856"
      - 
        key: "Last remote time (s)"
        value: "1626735553.488679886"
      - 
        key: "Estimated time offset (s)"
        value: "9223372036.854703903"
```

### Check ID

```
ERROR. I got 1 addresses, but not your target 1:1

---
Received 330 messages, from 1 addresses
sys:comp   list of messages
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 234, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/opt/ros/noetic/lib/mavros/checkid", line 82, in timer_cb
    for address, messages in self.message_sources.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

```

**Comment by Firestarss** [comment]
So uhh... I'm stupid and was providing the wrong port. The command should be `roslaunch mavros px4.launch fcu_url:=udp://:14550@192.168.2.1:14550` apparently. I can now issue commands. Apologies for potentially wasting anyone's time

**Comment by vooon** [comment]
NOTE: ArduSub is a variation of ArduPilot (ArduRover), not PX4.
