### ISSUE TITLE
MAVFTP:  IOError: service [/mavros/ftp/mkdir] unavailable

### ISSUE THREAD

**Issue by Rand0409** [mavlink/mavros#1779]
Hi, I am having some issue when I use the MAVFTP.
I ran these following commands:

 rosrun mavros mavftp list / 
 rosrun mavros mavftp download /APM/LOGS/00000001.BIN 
 rosrun mavros mavftp mkdir /APM/TERRAIN
 
### Issue details

Traceback (most recent call last):                                                                                        
File "/home/ws/src/mavros/mavros/scripts/mavftp", line 296, in <module> main()                                                                                                                File "/home/ws/src/mavros/mavros/scripts/mavftp", line 292, in main args.func(args)                                                                                                       File "/home/ws/src/mavros/mavros/scripts/mavftp", line 130, in do_mkdir ftp.mkdir(args.path)                                                                                                  File "/home/ws/src/mavros/mavros/src/mavros/ftp.py", line 190, in mkdir raise IOError(str(ex))                                                                                              **IOError: service [/mavros/ftp/mkdir] unavailable**

Similarlly I got **IOError: service [/mavros/ftp/open] unavailable**
                        **IOError: service [/mavros/ftp/open] unavailable**
                        **IOError: service [/mavros/ftp/list] unavailable**

### MAVROS version and platform

Mavros: 0.32.1
ROS: melodic
Ubuntu: Ubuntu 18.04.3 LTS

### Autopilot type and version

ArduPilot

Version: ArduCopter 4.0.7 (0bb18a15)

**Comment by Rand0409** [comment]
fixed.... didn't enable plugin
