### ISSUE TITLE
TypeError: cannot marshal None unless allow_none is enabled

### ISSUE THREAD

**Issue by hi6otb** [mavlink/mavros#1804]
This is only bug and feature tracker, please use it
to report bugs or request features.

----

### Issue details

I did "roslaunch mavros apm.launch" on JETSON NANO.
It says in the below.

---------------------------------------------------------

auto-starting new master
process[master]: started with pid [8245]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b43e5226-6941-11ed-b0e3-d0374517172c
process[rosout-1]: started with pid [8258]
started core service [/rosout]
load_parameters: unable to set parameters (last param was [/mavros/fake_gps/use_vision=False]): cannot marshal None unless allow_none is enabled
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 347, in main
    p.start()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 316, in start
    self.runner.launch()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/launch.py", line 676, in launch
    self._setup()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/launch.py", line 663, in _setup
    self._load_parameters()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/launch.py", line 354, in _load_parameters
    r  = param_server_multi()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1006, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1596, in __request
    allow_none=self.__allow_none)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1094, in dumps
    data = m.dumps(params)
  File "/usr/lib/python2.7/xmlrpclib.py", line 638, in dumps
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 719, in dump_array
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 741, in dump_struct
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 719, in dump_array
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 664, in dump_nil
    raise TypeError, "cannot marshal None unless allow_none is enabled"
TypeError: cannot marshal None unless allow_none is enabled
[rosout-1] killing on exit
[master] killing on exit

---------------------------------------------------------

### MAVROS version and platform

Mavros: ?1.14.0?
ROS: ?melodic?
Ubuntu: ?18.04?

### Autopilot type and version

[ x] ArduPilot
[  ] PX4

Version: ?3.7.1?

### Node logs

```
copy output of mavros_node. Usually console where you run roslaunch
```

### Diagnostics

```
place here result of:
rostopic echo -n1 /diagnostics
```

### Check ID

```
rosrun mavros checkid
```

**Comment by vooon** [comment]
It doesn't looks like mavros problem, as some core libs fails.
