### ISSUE TITLE
mavparam script can't dump parameters to file

### ISSUE THREAD

**Issue by srees** [mavlink/mavros#559]
Hello,

I've got a running PX4 SITL setup based off the latest masters, and wanted to get a list of parameters available to be set via ros.

I run:
`rosrun mavros mavparam dump -f params.txt`
I get:
```
Traceback (most recent call last):
  File "/home/sitl/catkin_ws/src/mavros/mavros/scripts/mavparam", line 103, in <module>
    main()
  File "/home/sitl/catkin_ws/src/mavros/mavros/scripts/mavparam", line 99, in main
    args.func(args)
  File "/home/sitl/catkin_ws/src/mavros/mavros/scripts/mavparam", line 44, in do_dump
    param_received, param_list = param_get_all(args.force)
  File "/home/sitl/catkin_ws/src/mavros/mavros/src/mavros/param.py", line 159, in param_get_all
    raise IOError(str(ex))
IOError: service [/mavros/param/pull] responded with an error: Character [_] is not valid as the first character in Graph Resource Name [_HASH_CHECK].  Valid characters are a-z, A-Z, / and in some cases ~.
```

**Comment by vooon** [comment]
Looks like there problem with rosparam and `_HASH_CHECK` param from PX4.

I see two possible ways to solve:
1) Do not use rosparam (more work to do, usage change)
2) Filter out `_HASH_CHECK'.

Ping @LorenzMeier, @mhkabir.
